<?php

namespace Database\Seeders;

use App\Models\AwardsRecognition;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class AwardsRecognitionSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();
        
        $awards = [
            // Excellence Awards
            [
                'title' => 'Municipal Excellence in Public Service Award 2024',
                'description' => 'Awarded for outstanding performance and dedication in public service delivery.',
                'awarding_body' => 'Department of Interior and Local Government',
                'category' => 'excellence',
                'award_date' => '2024-01-15',
                'received_date' => '2024-01-20',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Recognizes municipalities that demonstrate exceptional public service delivery and governance.',
                'criteria' => 'Performance metrics, citizen satisfaction, innovation in service delivery',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Government',
                'contact_person' => 'Mayor Juan Dela Cruz',
                'contact_email' => 'mayor@municipality.gov.ph',
                'contact_phone' => '+63 912 345 6789',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Innovation in Local Governance Award',
                'description' => 'Recognizing innovative approaches in local governance and public administration.',
                'awarding_body' => 'Local Government Academy',
                'category' => 'innovation',
                'award_date' => '2024-02-20',
                'received_date' => '2024-02-25',
                'location' => 'Quezon City, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Encourages innovation and modernization in local government operations.',
                'criteria' => 'Innovation impact, scalability, sustainability',
                'recipient_type' => 'department',
                'recipient_name' => 'Information Technology Department',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Green Municipality Award 2024',
                'description' => 'Awarded for exceptional environmental conservation and sustainability initiatives.',
                'awarding_body' => 'Department of Environment and Natural Resources',
                'category' => 'environment',
                'award_date' => '2024-03-10',
                'received_date' => '2024-03-15',
                'location' => 'Cebu City, Philippines',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Promotes environmental sustainability and conservation efforts.',
                'criteria' => 'Environmental projects, waste management, conservation efforts',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Environment and Natural Resources Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Best Tourism Destination Award',
                'description' => 'Recognized as the emerging tourism destination in the region.',
                'awarding_body' => 'Department of Tourism',
                'category' => 'tourism',
                'award_date' => '2024-01-30',
                'received_date' => '2024-02-05',
                'location' => 'Davao City, Philippines',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Boosts local tourism and economic development.',
                'criteria' => 'Tourism growth, visitor satisfaction, infrastructure development',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Tourism Office',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Outstanding Health Program Implementation',
                'description' => 'Awarded for excellent implementation of community health programs.',
                'awarding_body' => 'Department of Health',
                'category' => 'health',
                'award_date' => '2024-04-15',
                'received_date' => '2024-04-20',
                'location' => 'Iloilo City, Philippines',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Improves community health outcomes and healthcare access.',
                'criteria' => 'Health program coverage, impact assessment, community participation',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Health Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Education Excellence Award',
                'description' => 'Recognizing outstanding contributions to education and literacy programs.',
                'awarding_body' => 'Department of Education',
                'category' => 'education',
                'award_date' => '2024-05-20',
                'received_date' => '2024-05-25',
                'location' => 'Baguio City, Philippines',
                'award_type' => 'provincial',
                'scope' => 'provincial',
                'significance' => 'Enhances educational opportunities and literacy rates.',
                'criteria' => 'Literacy programs, school facilities, teacher development',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Education Department',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Business-Friendly LGU Award',
                'description' => 'Awarded for creating a conducive environment for business growth.',
                'awarding_body' => 'Department of Trade and Industry',
                'category' => 'business',
                'award_date' => '2024-06-10',
                'received_date' => '2024-06-15',
                'location' => 'Makati City, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Attracts investments and promotes economic development.',
                'criteria' => 'Ease of doing business, business permits processing, investor support',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Business Permits and Licensing Office',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Digital Transformation Champion',
                'description' => 'Recognized for excellence in digital governance and e-services.',
                'awarding_body' => 'Department of Information and Communications Technology',
                'category' => 'technology',
                'award_date' => '2024-07-05',
                'received_date' => '2024-07-10',
                'location' => 'Taguig City, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Promotes digitalization and modern governance.',
                'criteria' => 'Digital services, online transactions, technology adoption',
                'recipient_type' => 'department',
                'recipient_name' => 'Information Technology Department',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Community Safety and Peace Award',
                'description' => 'Awarded for outstanding achievements in maintaining peace and order.',
                'awarding_body' => 'Philippine National Police',
                'category' => 'safety',
                'award_date' => '2024-08-12',
                'received_date' => '2024-08-18',
                'location' => 'Camp Crame, Quezon City',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Ensures community safety and promotes peace.',
                'criteria' => 'Crime rate reduction, community policing, peace initiatives',
                'recipient_type' => 'team',
                'recipient_name' => 'Municipal Peace and Order Council',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Sustainable Agriculture Award',
                'description' => 'Recognized for promoting sustainable agricultural practices.',
                'awarding_body' => 'Department of Agriculture',
                'category' => 'sustainability',
                'award_date' => '2024-09-20',
                'received_date' => '2024-09-25',
                'location' => 'Nueva Ecija, Philippines',
                'award_type' => 'provincial',
                'scope' => 'provincial',
                'significance' => 'Supports agricultural development and food security.',
                'criteria' => 'Sustainable farming, crop yield improvement, farmer support',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Agriculture Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Heritage Conservation Award',
                'description' => 'Awarded for outstanding efforts in preserving cultural heritage.',
                'awarding_body' => 'National Historical Commission',
                'category' => 'community',
                'award_date' => '2024-10-15',
                'received_date' => '2024-10-20',
                'location' => 'Intramuros, Manila',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Preserves cultural heritage and historical sites.',
                'criteria' => 'Heritage conservation, cultural promotion, historical preservation',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Culture and Arts Council',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Disaster Resilience Award',
                'description' => 'Recognized for excellence in disaster preparedness and response.',
                'awarding_body' => 'National Disaster Risk Reduction and Management Council',
                'category' => 'safety',
                'award_date' => '2024-11-05',
                'received_date' => '2024-11-10',
                'location' => 'Pasig City, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Enhances community resilience to disasters.',
                'criteria' => 'Disaster preparedness, response efficiency, community training',
                'recipient_type' => 'team',
                'recipient_name' => 'Municipal DRRM Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Youth Development Excellence Award',
                'description' => 'Awarded for outstanding youth programs and development initiatives.',
                'awarding_body' => 'National Youth Commission',
                'category' => 'education',
                'award_date' => '2024-12-10',
                'received_date' => '2024-12-15',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Empowers youth and promotes their development.',
                'criteria' => 'Youth programs, participation rates, skill development',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Youth Development Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Quality Management System Certification',
                'description' => 'Awarded ISO 9001:2015 certification for quality management systems.',
                'awarding_body' => 'International Organization for Standardization',
                'category' => 'quality',
                'award_date' => '2024-03-25',
                'received_date' => '2024-04-01',
                'location' => 'Geneva, Switzerland',
                'award_type' => 'international',
                'scope' => 'international',
                'significance' => 'Demonstrates commitment to quality and continuous improvement.',
                'criteria' => 'Quality management system, process efficiency, customer satisfaction',
                'recipient_type' => 'organization',
                'recipient_name' => 'Municipal Quality Management Team',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'title' => 'Innovative Revenue Generation Award',
                'description' => 'Recognized for innovative approaches to local revenue generation.',
                'awarding_body' => 'Bureau of Local Government Finance',
                'category' => 'innovation',
                'award_date' => '2024-05-15',
                'received_date' => '2024-05-20',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Improves local government financial sustainability.',
                'criteria' => 'Revenue growth, collection efficiency, innovative methods',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Treasury Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Gender and Development Champion',
                'description' => 'Awarded for outstanding implementation of gender and development programs.',
                'awarding_body' => 'Philippine Commission on Women',
                'category' => 'community',
                'award_date' => '2024-06-25',
                'received_date' => '2024-06-30',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Promotes gender equality and women empowerment.',
                'criteria' => 'GAD programs, gender mainstreaming, women participation',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal GAD Focal Point System',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Best Public Market Award',
                'description' => 'Recognized as the cleanest and most organized public market in the region.',
                'awarding_body' => 'Department of the Interior and Local Government',
                'category' => 'service',
                'award_date' => '2024-07-20',
                'received_date' => '2024-07-25',
                'location' => 'Cebu City, Philippines',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Improves public market facilities and vendor welfare.',
                'criteria' => 'Cleanliness, organization, vendor satisfaction, customer service',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Market Administration',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Sports Development Award',
                'description' => 'Awarded for excellence in sports development and athlete support.',
                'awarding_body' => 'Philippine Sports Commission',
                'category' => 'community',
                'award_date' => '2024-08-30',
                'received_date' => '2024-09-05',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Promotes sports and physical fitness in the community.',
                'criteria' => 'Sports programs, athlete development, facilities improvement',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Sports Development Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Outstanding Senior Citizen Program',
                'description' => 'Recognized for excellent programs and services for senior citizens.',
                'awarding_body' => 'Department of Social Welfare and Development',
                'category' => 'service',
                'award_date' => '2024-10-05',
                'received_date' => '2024-10-10',
                'location' => 'Quezon City, Philippines',
                'award_type' => 'regional',
                'scope' => 'regional',
                'significance' => 'Supports welfare and well-being of senior citizens.',
                'criteria' => 'Senior citizen programs, participation, social services',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Social Welfare and Development Office',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'title' => 'Innovation in Solid Waste Management',
                'description' => 'Awarded for innovative approaches to solid waste management and recycling.',
                'awarding_body' => 'Environmental Management Bureau',
                'category' => 'innovation',
                'award_date' => '2024-11-20',
                'received_date' => '2024-11-25',
                'location' => 'Manila, Philippines',
                'award_type' => 'national',
                'scope' => 'national',
                'significance' => 'Promotes environmental sustainability through waste management.',
                'criteria' => 'Waste reduction, recycling programs, community participation',
                'recipient_type' => 'department',
                'recipient_name' => 'Municipal Environment and Natural Resources Office',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($awards as $award) {
            AwardsRecognition::create(array_merge($award, [
                'user_id' => $user->id,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]));
        }
    }
}