<?php
// database/seeders/BidsAwardsSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use App\Models\BidsAward;
use App\Models\User;

class BidsAwardsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the first user or create one if none exists
        $user = User::first() ?? User::factory()->create([
            'name' => 'Admin User',
            'email' => 'admin@example.com',
        ]);

        $bidsAwards = [
            [
                'title' => 'Construction of New Administrative Building',
                'description' => 'Construction of a 5-story administrative building including all civil works, electrical, plumbing, and finishing works.',
                'reference_number' => 'BID-2024-001',
                'bid_type' => 'open_tender',
                'estimated_budget' => 25000000.00,
                'bid_opening_date' => Carbon::now()->addDays(30),
                'bid_closing_date' => Carbon::now()->addDays(15),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => true,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['bid_document.pdf', 'technical_specs.docx']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Supply of Computer Equipment',
                'description' => 'Supply and delivery of 100 desktop computers, 50 laptops, and related peripherals for office use.',
                'reference_number' => 'BID-2024-002',
                'bid_type' => 'quotation',
                'estimated_budget' => 1500000.00,
                'bid_opening_date' => Carbon::now()->addDays(20),
                'bid_closing_date' => Carbon::now()->addDays(10),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['quotation_requirements.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Road Maintenance Project',
                'description' => 'Annual maintenance and repair of municipal roads including pothole patching and resurfacing.',
                'reference_number' => 'BID-2024-003',
                'bid_type' => 'open_tender',
                'estimated_budget' => 8000000.00,
                'bid_opening_date' => null,
                'bid_closing_date' => Carbon::now()->subDays(5),
                'award_date' => Carbon::now()->addDays(40),
                'status' => 'awarded',
                'is_featured' => true,
                'awarded_to' => 'ABC Construction Ltd.',
                'awarded_amount' => 7500000.00,
                'award_remarks' => 'Lowest bid meeting all technical requirements',
                'documents' => json_encode(['bid_evaluation_report.pdf', 'award_notice.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Office Furniture Supply',
                'description' => 'Supply of executive chairs, desks, filing cabinets, and conference room furniture.',
                'reference_number' => 'BID-2024-004',
                'bid_type' => 'closed_tender',
                'estimated_budget' => 500000.00,
                'bid_opening_date' => Carbon::now()->addDays(25),
                'bid_closing_date' => Carbon::now()->addDays(12),
                'award_date' => null,
                'status' => 'draft',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => null,
                'user_id' => $user->id,
            ],
            [
                'title' => 'Solar Power Installation Project',
                'description' => 'Design and installation of 500kW solar power system with battery storage for government complex.',
                'reference_number' => 'BID-2024-005',
                'bid_type' => 'open_tender',
                'estimated_budget' => 18000000.00,
                'bid_opening_date' => Carbon::now()->addDays(45),
                'bid_closing_date' => Carbon::now()->addDays(25),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => true,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['technical_specifications.pdf', 'bid_documents.zip']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'School Laboratory Equipment',
                'description' => 'Supply of science laboratory equipment for 10 secondary schools including chemicals and safety gear.',
                'reference_number' => 'BID-2024-006',
                'bid_type' => 'quotation',
                'estimated_budget' => 3200000.00,
                'bid_opening_date' => Carbon::now()->addDays(18),
                'bid_closing_date' => Carbon::now()->addDays(8),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['equipment_list.xlsx']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Water Treatment Plant Maintenance',
                'description' => 'Annual maintenance contract for municipal water treatment plant including chemical supply.',
                'reference_number' => 'BID-2024-007',
                'bid_type' => 'open_tender',
                'estimated_budget' => 9500000.00,
                'bid_opening_date' => null,
                'bid_closing_date' => Carbon::now()->subDays(5),
                'award_date' => Carbon::now()->addDays(15),
                'status' => 'evaluated',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['evaluation_committee_report.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Hospital Medical Equipment',
                'description' => 'Supply of MRI machine, X-ray equipment, and patient monitoring systems for regional hospital.',
                'reference_number' => 'BID-2024-008',
                'bid_type' => 'open_tender',
                'estimated_budget' => 45000000.00,
                'bid_opening_date' => Carbon::now()->addDays(60),
                'bid_closing_date' => Carbon::now()->addDays(40),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => true,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['technical_bid.pdf', 'financial_bid.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Fleet Vehicle Procurement',
                'description' => 'Purchase of 15 utility vehicles for various government departments.',
                'reference_number' => 'BID-2024-009',
                'bid_type' => 'closed_tender',
                'estimated_budget' => 12000000.00,
                'bid_opening_date' => null,
                'bid_closing_date' => Carbon::now()->subDays(15),
                'award_date' => Carbon::now()->addDays(5),
                'status' => 'awarded',
                'is_featured' => true,
                'awarded_to' => 'Prime Motors Ltd.',
                'awarded_amount' => 11500000.00,
                'award_remarks' => 'Most technically compliant bid with competitive pricing',
                'documents' => json_encode(['award_letter.pdf', 'contract_draft.docx']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'IT Network Infrastructure',
                'description' => 'Installation of fiber optic network and server infrastructure for government offices.',
                'reference_number' => 'BID-2024-010',
                'bid_type' => 'open_tender',
                'estimated_budget' => 2800000.00,
                'bid_opening_date' => Carbon::now()->addDays(35),
                'bid_closing_date' => Carbon::now()->addDays(20),
                'award_date' => null,
                'status' => 'draft',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => null,
                'user_id' => $user->id,
            ],
            [
                'title' => 'Waste Management Services',
                'description' => 'Three-year contract for municipal solid waste collection and disposal services.',
                'reference_number' => 'BID-2024-011',
                'bid_type' => 'open_tender',
                'estimated_budget' => 65000000.00,
                'bid_opening_date' => null,
                'bid_closing_date' => Carbon::now()->subDays(30),
                'award_date' => Carbon::now()->subDays(10),
                'status' => 'awarded',
                'is_featured' => false,
                'awarded_to' => 'EcoClean Solutions Inc.',
                'awarded_amount' => 62000000.00,
                'award_remarks' => 'Best value proposal with innovative recycling program',
                'documents' => json_encode(['contract_agreement.pdf', 'performance_bond.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Library Books Procurement',
                'description' => 'Supply of 10,000 books across various genres for public library system.',
                'reference_number' => 'BID-2024-012',
                'bid_type' => 'quotation',
                'estimated_budget' => 850000.00,
                'bid_opening_date' => Carbon::now()->addDays(22),
                'bid_closing_date' => Carbon::now()->addDays(12),
                'award_date' => null,
                'status' => 'published',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['book_catalog.pdf']),
                'user_id' => $user->id,
            ],
            [
                'title' => 'Security Services Contract',
                'description' => 'One-year contract for provision of armed security personnel at government facilities.',
                'reference_number' => 'BID-2024-013',
                'bid_type' => 'closed_tender',
                'estimated_budget' => 3500000.00,
                'bid_opening_date' => null,
                'bid_closing_date' => Carbon::now()->subDays(8),
                'award_date' => null,
                'status' => 'cancelled',
                'is_featured' => false,
                'awarded_to' => null,
                'awarded_amount' => null,
                'award_remarks' => null,
                'documents' => json_encode(['cancellation_notice.pdf']),
                'user_id' => $user->id,
            ]
        ];

        foreach ($bidsAwards as $bidAward) {
            BidsAward::updateOrCreate(
                ['reference_number' => $bidAward['reference_number']],
                $bidAward
            );
        }
    }
}