<?php
// database/seeders/TourismPackageSeeder.php

namespace Database\Seeders;

use App\Models\TourismPackage;
use App\Models\User;
use Illuminate\Database\Seeder;

class TourismPackageSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        $packages = [
            [
                'title' => 'Banaue Rice Terraces Adventure',
                'description' => 'Explore the magnificent Banaue Rice Terraces, a UNESCO World Heritage site, and immerse yourself in the rich culture of the Ifugao people.',
                'location' => 'Banaue, Ifugao',
                'category' => 'cultural',
                'price' => 12500.00,
                'duration_days' => 3,
                'duration_nights' => 2,
                'inclusions' => ['Accommodation', 'Meals', 'Local Guide', 'Transportation'],
                'exclusions' => ['Personal Expenses', 'Travel Insurance'],
                'difficulty_level' => 'moderate',
                'max_participants' => 15,
                'is_featured' => true,
                'is_active' => true,
                'contact_person' => 'Maria Santos',
                'contact_email' => 'tourism@banaue.com',
                'contact_phone' => '+639123456789',
            ],
            [
                'title' => 'Palawan Island Hopping',
                'description' => 'Discover the stunning islands of Palawan with crystal clear waters, hidden lagoons, and pristine beaches.',
                'location' => 'El Nido, Palawan',
                'category' => 'beach',
                'price' => 8500.00,
                'duration_days' => 4,
                'duration_nights' => 3,
                'inclusions' => ['Island Hopping', 'Snorkeling Gear', 'Lunch', 'Hotel Transfer'],
                'exclusions' => ['Airfare', 'Hotel Accommodation'],
                'difficulty_level' => 'easy',
                'max_participants' => 20,
                'is_featured' => true,
                'is_active' => true,
                'contact_person' => 'Juan Dela Cruz',
                'contact_email' => 'info@palawantours.com',
                'contact_phone' => '+639987654321',
            ],
            [
                'title' => 'Mount Pulag Summit Trek',
                'description' => 'Experience the breathtaking sea of clouds from the summit of Mount Pulag, the third highest mountain in the Philippines.',
                'location' => 'Kabayan, Benguet',
                'category' => 'mountain',
                'price' => 3500.00,
                'duration_days' => 2,
                'duration_nights' => 1,
                'inclusions' => ['Camping Gear', 'Meals', 'Local Guide', 'Environmental Fee'],
                'exclusions' => ['Transportation to Jump-off', 'Personal Gear'],
                'difficulty_level' => 'difficult',
                'max_participants' => 12,
                'is_featured' => false,
                'is_active' => true,
                'contact_person' => 'Pedro Gomez',
                'contact_email' => 'treks@pulag.com',
                'contact_phone' => '+639456123789',
            ],
            [
                'title' => 'Vigan Heritage Walk',
                'description' => 'Step back in time and explore the well-preserved Spanish colonial architecture in the historic city of Vigan.',
                'location' => 'Vigan, Ilocos Sur',
                'category' => 'heritage',
                'price' => 2800.00,
                'duration_days' => 1,
                'duration_nights' => 0,
                'inclusions' => ['Heritage Tour', 'Lunch', 'Calesa Ride', 'Museum Fees'],
                'exclusions' => ['Hotel Accommodation', 'Transportation'],
                'difficulty_level' => 'easy',
                'max_participants' => 25,
                'is_featured' => false,
                'is_active' => true,
                'contact_person' => 'Carmen Reyes',
                'contact_email' => 'heritage@vigan.com',
                'contact_phone' => '+639789456123',
            ],
            [
                'title' => 'Cebu Food Crawl',
                'description' => 'Taste the best of Cebuano cuisine from street food to fine dining in this culinary adventure.',
                'location' => 'Cebu City',
                'category' => 'food',
                'price' => 2200.00,
                'duration_days' => 1,
                'duration_nights' => 0,
                'inclusions' => ['Food Tastings', 'Local Guide', 'Transportation between stops'],
                'exclusions' => ['Additional Food Orders', 'Alcoholic Drinks'],
                'difficulty_level' => 'easy',
                'max_participants' => 15,
                'is_featured' => true,
                'is_active' => true,
                'contact_person' => 'Luis Tan',
                'contact_email' => 'food@cebutours.com',
                'contact_phone' => '+639321654987',
            ],
            [
                'title' => 'Davao Eco Adventure',
                'description' => 'Experience the biodiversity of Davao with visits to eco-parks, wildlife sanctuaries, and organic farms.',
                'location' => 'Davao City',
                'category' => 'eco_tourism',
                'price' => 5200.00,
                'duration_days' => 2,
                'duration_nights' => 1,
                'inclusions' => ['Park Entrances', 'Meals', 'Eco Guide', 'Hotel Accommodation'],
                'exclusions' => ['Airfare', 'Personal Shopping'],
                'difficulty_level' => 'moderate',
                'max_participants' => 18,
                'is_featured' => false,
                'is_active' => true,
                'contact_person' => 'Ana Dizon',
                'contact_email' => 'eco@davaotours.com',
                'contact_phone' => '+639654987321',
            ],
            [
                'title' => 'Siargao Surf Camp',
                'description' => 'Learn to surf in the surfing capital of the Philippines with professional instructors and perfect waves.',
                'location' => 'General Luna, Siargao',
                'category' => 'adventure',
                'price' => 6800.00,
                'duration_days' => 5,
                'duration_nights' => 4,
                'inclusions' => ['Surf Lessons', 'Board Rental', 'Accommodation', 'Breakfast'],
                'exclusions' => ['Lunch and Dinner', 'Island Hopping'],
                'difficulty_level' => 'moderate',
                'max_participants' => 10,
                'is_featured' => true,
                'is_active' => true,
                'contact_person' => 'Kai Santos',
                'contact_email' => 'surf@siargao.com',
                'contact_phone' => '+639147258369',
            ],
            [
                'title' => 'Bohol Countryside Tour',
                'description' => 'Discover the natural wonders of Bohol including the Chocolate Hills, tarsier sanctuary, and Loboc River.',
                'location' => 'Bohol Province',
                'category' => 'cultural',
                'price' => 3200.00,
                'duration_days' => 1,
                'duration_nights' => 0,
                'inclusions' => ['Transportation', 'Lunch Cruise', 'Entrance Fees', 'Guide'],
                'exclusions' => ['Hotel Accommodation', 'Additional Activities'],
                'difficulty_level' => 'easy',
                'max_participants' => 20,
                'is_featured' => false,
                'is_active' => true,
                'contact_person' => 'Rosa Alcantara',
                'contact_email' => 'tours@bohol.com',
                'contact_phone' => '+639258147369',
            ],
            [
                'title' => 'Sagada Cave Connection',
                'description' => 'Explore the interconnected cave system of Sagada with experienced local guides and spelunking equipment.',
                'location' => 'Sagada, Mountain Province',
                'category' => 'adventure',
                'price' => 1800.00,
                'duration_days' => 1,
                'duration_nights' => 0,
                'inclusions' => ['Guide Fee', 'Equipment Rental', 'Entrance Fee'],
                'exclusions' => ['Transportation', 'Meals', 'Accommodation'],
                'difficulty_level' => 'difficult',
                'max_participants' => 8,
                'is_featured' => false,
                'is_active' => true,
                'contact_person' => 'Ben Magalong',
                'contact_email' => 'adventure@sagada.com',
                'contact_phone' => '+639369258147',
            ],
            [
                'title' => 'Tagaytay Wellness Retreat',
                'description' => 'Rejuvenate your mind and body with yoga sessions, spa treatments, and healthy cuisine overlooking Taal Volcano.',
                'location' => 'Tagaytay City',
                'category' => 'wellness',
                'price' => 7500.00,
                'duration_days' => 2,
                'duration_nights' => 1,
                'inclusions' => ['Yoga Sessions', 'Spa Treatments', 'Healthy Meals', 'Accommodation'],
                'exclusions' => ['Transportation', 'Additional Services'],
                'difficulty_level' => 'easy',
                'max_participants' => 12,
                'is_featured' => true,
                'is_active' => true,
                'contact_person' => 'Sofia Lim',
                'contact_email' => 'wellness@tagaytay.com',
                'contact_phone' => '+639741852963',
            ],
        ];

        foreach ($packages as $package) {
            TourismPackage::create(array_merge($package, [
                'user_id' => $user->id,
                'itinerary' => $this->generateSampleItinerary(),
            ]));
        }
    }

    private function generateSampleItinerary()
    {
        return [
            ['time' => '08:00 AM', 'activity' => 'Meet up and orientation'],
            ['time' => '09:00 AM', 'activity' => 'Start of main activity'],
            ['time' => '12:00 PM', 'activity' => 'Lunch break'],
            ['time' => '01:00 PM', 'activity' => 'Continue activities'],
            ['time' => '05:00 PM', 'activity' => 'Wrap up and departure'],
        ];
    }
}